
package co.edu.javeriana.eko.xml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IProductoService", targetNamespace = "http://iservice.eko.javeriana.edu.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IProductoService {


    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calificacionPromedio", targetNamespace = "http://iservice.eko.javeriana.edu.co/", className = "co.edu.javeriana.eko.xml.CalificacionPromedio")
    @ResponseWrapper(localName = "calificacionPromedioResponse", targetNamespace = "http://iservice.eko.javeriana.edu.co/", className = "co.edu.javeriana.eko.xml.CalificacionPromedioResponse")
    @Action(input = "http://iservice.eko.javeriana.edu.co/IProductoService/calificacionPromedioRequest", output = "http://iservice.eko.javeriana.edu.co/IProductoService/calificacionPromedioResponse")
    public double calificacionPromedio();

    /**
     * 
     * @param transporte
     */
    @WebMethod
    @RequestWrapper(localName = "agregarProductoTransporte", targetNamespace = "http://iservice.eko.javeriana.edu.co/", className = "co.edu.javeriana.eko.xml.AgregarProductoTransporte")
    @ResponseWrapper(localName = "agregarProductoTransporteResponse", targetNamespace = "http://iservice.eko.javeriana.edu.co/", className = "co.edu.javeriana.eko.xml.AgregarProductoTransporteResponse")
    @Action(input = "http://iservice.eko.javeriana.edu.co/IProductoService/agregarProductoTransporteRequest", output = "http://iservice.eko.javeriana.edu.co/IProductoService/agregarProductoTransporteResponse")
    public void agregarProductoTransporte(
        @WebParam(name = "transporte", targetNamespace = "")
        Transporte transporte);

    /**
     * 
     * @param transporteID
     */
    @WebMethod
    @RequestWrapper(localName = "buscarProductoTransportePorID", targetNamespace = "http://iservice.eko.javeriana.edu.co/", className = "co.edu.javeriana.eko.xml.BuscarProductoTransportePorID")
    @ResponseWrapper(localName = "buscarProductoTransportePorIDResponse", targetNamespace = "http://iservice.eko.javeriana.edu.co/", className = "co.edu.javeriana.eko.xml.BuscarProductoTransportePorIDResponse")
    @Action(input = "http://iservice.eko.javeriana.edu.co/IProductoService/buscarProductoTransportePorIDRequest", output = "http://iservice.eko.javeriana.edu.co/IProductoService/buscarProductoTransportePorIDResponse")
    public void buscarProductoTransportePorID(
        @WebParam(name = "transporteID", targetNamespace = "")
        String transporteID);

    /**
     * 
     * @param transporteID
     */
    @WebMethod
    @RequestWrapper(localName = "eliminarProductoTransportePorID", targetNamespace = "http://iservice.eko.javeriana.edu.co/", className = "co.edu.javeriana.eko.xml.EliminarProductoTransportePorID")
    @ResponseWrapper(localName = "eliminarProductoTransportePorIDResponse", targetNamespace = "http://iservice.eko.javeriana.edu.co/", className = "co.edu.javeriana.eko.xml.EliminarProductoTransportePorIDResponse")
    @Action(input = "http://iservice.eko.javeriana.edu.co/IProductoService/eliminarProductoTransportePorIDRequest", output = "http://iservice.eko.javeriana.edu.co/IProductoService/eliminarProductoTransportePorIDResponse")
    public void eliminarProductoTransportePorID(
        @WebParam(name = "transporteID", targetNamespace = "")
        String transporteID);

}
