
package co.edu.javeriana.eko.xml;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MarketPlaceWebServicesService", targetNamespace = "http://webservices.eko.javeriana.edu.co/", wsdlLocation = "http://localhost:8080/eko/market-place?wsdl")
public class MarketPlaceWebServicesService
    extends Service
{

    private final static URL MARKETPLACEWEBSERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException MARKETPLACEWEBSERVICESSERVICE_EXCEPTION;
    private final static QName MARKETPLACEWEBSERVICESSERVICE_QNAME = new QName("http://webservices.eko.javeriana.edu.co/", "MarketPlaceWebServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/eko/market-place?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MARKETPLACEWEBSERVICESSERVICE_WSDL_LOCATION = url;
        MARKETPLACEWEBSERVICESSERVICE_EXCEPTION = e;
    }

    public MarketPlaceWebServicesService() {
        super(__getWsdlLocation(), MARKETPLACEWEBSERVICESSERVICE_QNAME);
    }

    public MarketPlaceWebServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MARKETPLACEWEBSERVICESSERVICE_QNAME, features);
    }

    public MarketPlaceWebServicesService(URL wsdlLocation) {
        super(wsdlLocation, MARKETPLACEWEBSERVICESSERVICE_QNAME);
    }

    public MarketPlaceWebServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MARKETPLACEWEBSERVICESSERVICE_QNAME, features);
    }

    public MarketPlaceWebServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarketPlaceWebServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMarketPlace
     */
    @WebEndpoint(name = "MarketPlaceWebServicesPort")
    public IMarketPlace getMarketPlaceWebServicesPort() {
        return super.getPort(new QName("http://webservices.eko.javeriana.edu.co/", "MarketPlaceWebServicesPort"), IMarketPlace.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMarketPlace
     */
    @WebEndpoint(name = "MarketPlaceWebServicesPort")
    public IMarketPlace getMarketPlaceWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.eko.javeriana.edu.co/", "MarketPlaceWebServicesPort"), IMarketPlace.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MARKETPLACEWEBSERVICESSERVICE_EXCEPTION!= null) {
            throw MARKETPLACEWEBSERVICESSERVICE_EXCEPTION;
        }
        return MARKETPLACEWEBSERVICESSERVICE_WSDL_LOCATION;
    }

}
