
package co.edu.javeriana.eko.xml;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductoWebServicesService", targetNamespace = "http://webservices.eko.javeriana.edu.co/", wsdlLocation = "http://localhost:8080/eko/producto?wsdl")
public class ProductoWebServicesService
    extends Service
{

    private final static URL PRODUCTOWEBSERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTOWEBSERVICESSERVICE_EXCEPTION;
    private final static QName PRODUCTOWEBSERVICESSERVICE_QNAME = new QName("http://webservices.eko.javeriana.edu.co/", "ProductoWebServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/eko/producto?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTOWEBSERVICESSERVICE_WSDL_LOCATION = url;
        PRODUCTOWEBSERVICESSERVICE_EXCEPTION = e;
    }

    public ProductoWebServicesService() {
        super(__getWsdlLocation(), PRODUCTOWEBSERVICESSERVICE_QNAME);
    }

    public ProductoWebServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTOWEBSERVICESSERVICE_QNAME, features);
    }

    public ProductoWebServicesService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTOWEBSERVICESSERVICE_QNAME);
    }

    public ProductoWebServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTOWEBSERVICESSERVICE_QNAME, features);
    }

    public ProductoWebServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductoWebServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IProductoService
     */
    @WebEndpoint(name = "ProductoWebServicesPort")
    public IProductoService getProductoWebServicesPort() {
        return super.getPort(new QName("http://webservices.eko.javeriana.edu.co/", "ProductoWebServicesPort"), IProductoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IProductoService
     */
    @WebEndpoint(name = "ProductoWebServicesPort")
    public IProductoService getProductoWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.eko.javeriana.edu.co/", "ProductoWebServicesPort"), IProductoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTOWEBSERVICESSERVICE_EXCEPTION!= null) {
            throw PRODUCTOWEBSERVICESSERVICE_EXCEPTION;
        }
        return PRODUCTOWEBSERVICESSERVICE_WSDL_LOCATION;
    }

}
